api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
# router.register(r'posts', views.PostViewSet)
# router.register(r'comments', views.CommentViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('posts/', views.PostListView.as_view()),
    path('comments/', views.CommentListView.as_view()),
    path('comment-create/', views.CommentCreateView.as_view()),
    path('comment-update/<int:pk>/', views.CommentUpdateDeleteView.as_view()),
    path('post-create/', views.PostCreateView.as_view()),
    path('post-update/<int:pk>/', views.PostUpdateDeleteView.as_view(), name='manufacturers'),
    path('register/', views.UserCreateView.as_view()),
    

]

blueprint/urls.py
from tkinter import N
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('store/', include('store.urls', namespace='store')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.main, name="store_index"),
    path('filter/', views.FilterListView.as_view(), name='filter'),
    path('products/', views.ProductListView.as_view(), name="store_products"),
    path('category/<str:category>', views.FilterListView.as_view(), name="category"),
    path('product/<int:pk>', views.single_product, name="product"),
    path('order/', views.order_process_view, name="order"),
    path('cart/', views.cart_view, name="cart"),
    path('remove/<int:id>/', views.cart_remove, name='cart_remove'),
    path('update/<int:id>/', views.cart_update, name='cart_update'),
    path('checkout/', views.order_address, name='checkout'),
    # path('payment', views.payment_process, name='payment'),
    path('process/', views.payment_process, name='process'),
    path('done/', views.payment_done, name='done'),
    path('canceled/', views.payment_canceled, name='canceled'),
]

store/forms.py
from django import forms
from .models import Order, ProductReview

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CustomSelectWidget(forms.Select):
    template_name = 'store/tst.html'


class OrderForm(forms.Form):

    '''in the single_product view, we pass the product instance to the form.'''
    def __init__(self, instance, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.instance = instance
        
        self.fields['size'] = forms.ModelChoiceField(
            queryset=self.instance.sizes.all(),
            widget=forms.RadioSelect())
        
        self.fields['quantity'] = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}), initial=1)

class ReviewForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        
        #remove help text from form fields
        for field in self.fields:
            self.fields[field].label = ''

    class Meta:
        model = ProductReview
        fields = ['name', 'email', 'comment',]
        widgets = {'name': forms.widgets.TextInput(attrs={
                   'placeholder': 'Name'}),
                'email': forms.widgets.TextInput(attrs={
                    "placeholder": 'Email'}),
                'comment': forms.widgets.Textarea(attrs={
                    "placeholder": 'Review', "rows": "5"}),
               }


class OrderAddressForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'country', 'city', 'address', 'postal_code']

store/views.py
from decimal import Decimal
from django.db.models import Count
from django.db.models import Q
from django.db.models.expressions import F
from django.shortcuts import get_object_or_404, render, redirect
from .models import Order, Product, ProductReview, Categories, Types, Size, CartItem, Coupon
from .forms import OrderAddressForm, ReviewForm, OrderForm
from django.db.models import Avg
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.views.generic.list import ListView
from django.core.exceptions import EmptyResultSet
import braintree
from django.conf import settings

gateway = braintree.BraintreeGateway(settings.BRAINTREE_CONF)
# Create your views here.


def main(request):
    categories = Categories.objects.all()
    mens = Product.objects.filter(category=1).order_by('-date_added')[:7]
    womens = Product.objects.filter(category=2).order_by('-date_added')[:7]
    kids = Product.objects.filter(category=3).order_by('-date_added')[:7]
    return render(request, 'store/index.html', {'categories': categories, "mens": mens, "kids": kids, "womens": womens})


class CategTypeAndSize:
    '''provides categ., type, and size to html filter sidebar via 
    'get_...()' through FilterListView and ProductListView inheritance.'''
    def get_category(self):
        return Categories.objects.all()

    def get_type(self):
        return Types.objects.all()

    def get_size(self):
        return Size.objects.all()


    
class FilterListView(CategTypeAndSize, ListView):
    '''inherits CategTypeAndSize in order to display info in filter sidebar
    on both loads of store/products.html: 1 - from loading all products via 
    ProductListView and 2 - after filtering products from this view.'''
    template_name = 'store/products.html'
    context_object_name = 'products'
    paginate_by = 9

    def get_queryset(self):
        if self.kwargs.get('category'):
            '''if the view is accessed from url 'category/<str:category>'. It passes 
            str of men/women/kids/accessories to view. get_queryset() filters 'Category' objects 
            by 'category' capitalized variable. 'category' gets passed in lowercase. The DB 'Category' 
            models are capitalized. Either call .capitalize() on the category variable or change 
            DB models to lowercase.'''
            return Product.objects.filter(category__category=(self.kwargs.get('category')).capitalize())  
        else:
            '''if no 'category' is passed, the view is accessed from /filter url. 
            The view returns Product objects to html by generating QS from the data 
            in the GET parameters of the sidebar form in the store/products.html.'''
            try:
                '''Simply listing the Q objects with a comma in the Product.objects.filter(...) call 
                does not work in the occasion when only one or two keywords are being filteres. 
                That's why a check is necessary for every keyword. If it is present in the request.GET, 
                an empty Q object is extended with the according filter word. The filtering is then 
                executed on the entire Q obj, which can have 1, 2, 3 or none of the keywords.'''
                q_obj = Q()
                if 'category' in self.request.GET:
                    q_obj.add(Q(category__in=self.request.GET.getlist('category')), Q.AND)
                if 'type' in self.request.GET:
                    q_obj.add(Q(product_type__in=self.request.GET.getlist('type')), Q.AND)
                if 'size' in self.request.GET:
                    q_obj.add(Q(sizes__in=self.request.GET.getlist('size')), Q.AND)
                qs = Product.objects.filter(q_obj)
                return qs
            except EmptyResultSet:
                pass


class ProductListView(CategTypeAndSize, ListView):
    '''inherits CategTypeAndSize in order to display info in filter sidebar
    on both loads of store/products.html: 1 - from loading all products from this view
    and 2 - after filtering products via FilterListView.'''
    model = Product
    template_name = 'store/products.html'
    context_object_name = 'products'
    paginate_by = 9


def single_product(request, pk):
    product = get_object_or_404(Product, pk=pk)

    #returns {'rating__avg': 3.6666666666666665} f. eg.
    avg_prod_rating = product.product_reviews.all().aggregate(Avg('rating'))['rating__avg']

    # uses .count() instead of len() - faster in DB! len() will retrieve a QS w/ the objects;
    # count() will perform an SQL COUNT and will not load the objects into memory to count them.
    five_star = product.product_reviews.filter(rating=5).count()
    four_star = product.product_reviews.filter(rating=4).count()
    three_star = product.product_reviews.filter(rating=3).count()
    two_star = product.product_reviews.filter(rating=2).count()
    one_star = product.product_reviews.filter(rating=1).count()
    ratings = {'os': one_star, 'ts': two_star, 'trs': three_star, 'fs': four_star, 'fvs': five_star}

    #similar products:
    product_tags_ids = product.tags.values_list('id', flat=True)
    similar_products = Product.objects.filter(tags__in=product_tags_ids).exclude(id=product.id)
    similar_products = similar_products.annotate(same_tags=Count('tags')).order_by('-same_tags',)
    #end

    reviews = product.product_reviews.all()

    
    if request.method == 'POST':
        #Reviews:
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            # directly create product instance from data from 
            # store.forms.ReviewForm AND! the raw HTML rating_val star inputs.
            new_review = ProductReview(name=review_form.cleaned_data['name'], product=product, 
                          email=review_form.cleaned_data['email'], comment=review_form.cleaned_data['comment'], 
                          rating=int(request.POST['rating_val']))
            new_review.save()
            product.rating = avg_prod_rating
            product.save()

            #redirect to the same page to avoid form resubmission on reload.
            return redirect(product.get_absolute_url())

    #Add to cart (uses GET):
    order_form = OrderForm(product)
    
    # paginator = Paginator(reviews, 1)
    # page_number = request.GET.get('page')
    # page_obj = paginator.get_page(page_number)
        
    review_form = ReviewForm()
    context = {'product': product, 'order_form': order_form, 'review_form': review_form,
               'reviews': reviews, 'avg_prod_rating': avg_prod_rating, 'similar_products': similar_products}

    #update context dict w/ ratings dict.
    context.update(ratings)
    return render(request, 'store/single-product.html', context)


def order_process_view(request):
    product_id = int(request.GET.get('product'))
    size_id = int(request.GET.get('size'))
    quantity = int(request.GET.get('quantity'))

    #clear cart:
    # del request.session['cart']
    cart = request.session.get('cart')
    if not cart:
        cart = []
    for cart_id in cart:
        cart_obj = CartItem.objects.get(id=cart_id)
        
        if cart_obj.product.id == product_id:
            if cart_obj.product_size.id == size_id:
                cart_obj.quantity += quantity
                cart_obj.save()
                break
    else:
        new_cart_item = CartItem.objects.create(product=Product.objects.get(id=product_id), 
                                    product_size=Size.objects.get(id=size_id), 
                                    quantity=quantity)
        cart.append(new_cart_item.id)

    request.session['cart'] = cart
    return redirect('store:cart')


def cart_view(request):
    try:
        cart = request.session['cart']
    except Exception as e:
        return render(request, 'store/cart.html')

    context = {"cart_objects": [],}
    total_price = 0

    for item_id in cart:
        order_item = CartItem.objects.get(id=item_id)
        total_price += order_item.get_cost()
        context["cart_objects"].append(order_item)

    code = request.GET.get('code')
    if code is not None:
        coupon = Coupon.objects.get(code=code)
        # necessary to do it this way because of TypeError: 
        # unsupported operand type(s) for *: 'decimal.Decimal' and 'float'. 
        discount = round(total_price*round(Decimal(coupon.discount/100), 2),2)
        total_price -= discount
        context['coupon'] = coupon
        request.session['coupon'] = coupon.code

    context['total_price'] = total_price
        
    return render(request, 'store/cart.html', context)



def cart_remove(request, id):
    cart = request.session.get('cart')
    cart.remove(id)
    request.session['cart'] = cart
    return redirect('store:cart')


def cart_update(request, id):
    cart_item = CartItem.objects.get(id=id)
    cart_item.quantity = request.GET.get('quantity')
    cart_item.save()
    return redirect('store:cart')


def order_address(request):
    if not request.session['cart']:
        return render(request, 'store/index.html')
    form = OrderAddressForm()
    if request.method == 'POST':
        form = OrderAddressForm(request.POST)
        if form.is_valid():

            cart_items = []
            for item_id in request.session['cart']:
                order_item = CartItem.objects.get(id=item_id)
                cart_items.append(order_item)

        new_order = Order(cartitem=cart_items[0], 
                                        first_name=request.POST['first_name'],
                                        last_name = request.POST['last_name'],
                                        country = request.POST['country'],
                                        city = request.POST['city'],
                                        address = request.POST['address'],
                                        postal_code = request.POST['postal_code'])
        try:
        # if request.session['coupon']:

store/templates/store/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>Hexashop Ecommerce HTML CSS Template</title>

    <!-- VERY IMPORTANT - JS CAROUSEL WON'T WORK W/O IT! -->
    <script src="{% static "assets/js/jquery-2.1.0.min.js" %}"></script>

    <!-- Additional CSS Files -->
    <link rel="stylesheet" type="text/css" href="{% static "assets/css/bootstrap.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "assets/css/font-awesome.css" %}">

    <link rel="stylesheet" href="{% static "assets/css/templatemo-hexashop.css" %}">

    <link rel="stylesheet" href="{% static "assets/css/owl-carousel.css" %}">

    <link rel="stylesheet" href="{% static "assets/css/lightbox.css" %}">
<!--

TemplateMo 571 Hexashop

https://templatemo.com/tm-571-hexashop

-->
    </head>
    
    <body>
    
    <!-- ***** Preloader Start ***** -->
    <!-- <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>   -->
    <!-- ***** Preloader End ***** -->
    
    
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="{% url "store:store_index" %}" class="logo">
                            <img src="{% static "assets/images/logo.png" %}">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li class="scroll-to-section"><a href="{% url "store:store_index" %}" class="{% if request.path == '/store/' %}active{% endif %}">Home</a></li>
                            <li class="scroll-to-section"><a href="{% url "store:category" 'men' %}" class="{% if 'men' in request.path and 'women' not in request.path %}active{% endif %}">Men's</a></li>
                            <li class="scroll-to-section"><a href="{% url "store:category" 'women' %}" class="{% if 'women' in request.path %}active{% endif %}">Women's</a></li>
                            <li class="scroll-to-section"><a href="{% url "store:category" 'kids' %}" class="{% if 'kids' in request.path %}active{% endif %}">Kid's</a></li>
                            <li class="submenu">
                                <a href="javascript:;" class="{% if 'product' in request.path %}active{% endif %}">Pages</a>
                                <ul>
                                    <li><a href="{% url "store:store_products" %}">Products</a></li>
                                </ul>
                            </li>
                            <li class="submenu">
                                <a href="javascript:;">Features</a>
                                <ul>
                                    <li><a href="#">Features Page 1</a></li>
                                    <li><a href="#">Features Page 2</a></li>
                                    <li><a href="#">Features Page 3</a></li>
                                    <li><a rel="nofollow" href="https://templatemo.com/page/4" target="_blank">Template Page 4</a></li>
                                </ul>
                            </li>
                        </ul>        
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->

    <!-- ***** Main Banner Area Start ***** -->
    
    {% block content %}
    
    {% endblock %}
    
    <!-- ***** Footer Start ***** -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="first-item">
                        <div class="logo">
                            <img src="{% static "assets/images/white-logo.png" %}" alt="hexashop ecommerce templatemo">
                        </div>
                        <ul>
                            <li><a href="#">16501 Collins Ave, Sunny Isles Beach, FL 33160, United States</a></li>
                            <li><a href="#">hexashop@company.com</a></li>
                            <li><a href="#">010-020-0340</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3">
                    <h4>Shopping &amp; Categories</h4>
                    <ul>
                        <li><a href="#">Men’s Shopping</a></li>
                        <li><a href="#">Women’s Shopping</a></li>
                        <li><a href="#">Kid's Shopping</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><a href="#">Homepage</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h4>Help &amp; Information</h4>
                    <ul>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">FAQ's</a></li>
                        <li><a href="#">Shipping</a></li>
                        <li><a href="#">Tracking ID</a></li>
                    </ul>
                </div>
                <div class="col-lg-12">
                    <div class="under-footer">
                        <p>Copyright © 2022 HexaShop Co., Ltd. All Rights Reserved. 
                        
                        <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">TemplateMo</a></p>
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-behance"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    

    <!-- jQuery -->
    <script src="{% static "assets/js/jquery-2.1.0.min.js" %}"></script>

    <!-- Bootstrap -->
    <script src="{% static "assets/js/popper.js" %}"></script>
    <script src="{% static "assets/js/bootstrap.min.js" %}"></script>

    <!-- Plugins -->
    <script src="{% static "assets/js/owl-carousel.js" %}"></script>
    <script src="{% static "assets/js/accordions.js" %}"></script>
    <script src="{% static "assets/js/datepicker.js" %}"></script>
    <script src="{% static "assets/js/scrollreveal.min.js" %}"></script>
    <script src="{% static "assets/js/waypoints.min.js" %}"></script>
    <script src="{% static "assets/js/jquery.counterup.min.js" %}"></script>
    <script src="{% static "assets/js/imgfix.min.js" %}"></script> 
    <script src="{% static "assets/js/slick.js" %}"></script> 
    <script src="{% static "assets/js/lightbox.js" %}"></script> 
    <script src="{% static "assets/js/isotope.js" %}"></script> 
    
    <!-- Global Init -->
    <script src="{% static "assets/js/custom.js" %}"></script>

    <script>

        $(function() {
            var selectedClass = "";
            $("p").click(function(){
            selectedClass = $(this).attr("data-rel");
            $("#portfolio").fadeTo(50, 0.1);
                $("#portfolio div").not("."+selectedClass).fadeOut();
            setTimeout(function() {
              $("."+selectedClass).fadeIn();
              $("#portfolio").fadeTo(50, 1);
            }, 500);
                
            });
        });

    </script>

  </body>
</html>

store/templates/store/canceled.html
{% extends "store/base.html" %}
{% block content %}
<div class="container" style="margin-top: 15%; margin-bottom: 20%;">
    <h1>Your payment has not been processed</h1>
    <p>There was a problem processing your payment.</p>
</div>
{% endblock %}

store/templates/store/cart.html
{% extends 'store/base.html' %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <!-- CART area -->
    
    <div class="shop-card">
        <div class="row">
            <div class="col-md-8 cart">
                <div class="title">
                    <div class="row">
                        <div class="col">
                            <h4><b>Shopping Cart</b></h4>
                        </div>
                        <div class="col align-self-center text-right text-muted">{{ cart_objects|length }} item{{ cart_objects|pluralize }}</div>
                    </div>
                </div>

                {% for item in cart_objects %}
                    <!-- <form action="{% url 'store:cart' %}"> -->
                            <div class="row border-top border-bottom">
                                <div class="row main align-items-center">
                                    <div class="col-2"><img class="img-fluid" src="{{ item.product.product_images.first.image.url }}"></div>
                                    <div class="col">
                                        <div class="row text-muted">{{ item.product.product_type }}</div>
                                        <div class="row">{{ item.product }}</div>
                                    </div>
                                    <div class="col" >Size {{ item.product_size }}</div>
                                    <div>
                                        <form action="{% url "store:cart_update" item.id %}">

                                            <input style="margin-bottom: 0; width: 7em; float: left;" class="form-control" type="number" id="quantity" name="quantity" value="{{ item.quantity }}">
                                            <input style="margin-right: 50px; float:right" class="close" type="submit" value="&#10003">
                                        </form>
                                    </div>
                                    <div class="col">&euro; {{ item.product.price }}</div>
                                    <form action="{% url "store:cart_remove" item.id %}">
                                        <input class="close" type="submit" value="&#10005;">
                                    </form>
                                    
                                </div>                        
                            </div>
                            {{item.product.get_cost}}
                {% endfor %}
                
                
                
                <div class="back-to-shop"><a href="{% url "store:store_products" %}"><span class="text-muted">&leftarrow; Back to shop</span></a></div>
            </div>
            <div class="col-md-4 summary">
                <div>
                    <h5><b>Summary</b></h5>
                </div>
                <hr>
                <div class="row">
                    <div class="col" style="padding-left:0;">{{ cart_objects|length }} ITEM{{ cart_objects|pluralize|capfirst }}</div>
                    <div class="col text-right">&euro; {{ total_price }}</div>
                </div>
                <form action="{% url "store:cart" %}">
                    <p>SHIPPING</p> <select>
                        <option class="text-muted">Standard-Delivery- &euro;5.00</option>
                    </select>
                    <p>GIVE CODE</p> <input name="code" placeholder="Enter your code">
                    {% if coupon %}
                        <p>Applied coupon {{ coupon }}</p>
                    {% endif %}
                </form>
                <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
                    <div class="col">TOTAL PRICE</div>
                    
                    <div class="col text-right">&euro; {{ total_price }}</div>
                    
                </div>                 
                
                {% if cart_objects|length == 0 %}
                    <button type="button" style="background-color: grey;" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="bottom" title="You do not have items in your cart.">CHECKOUT</button>
                {% else %}
                    <button onclick=window.location="{% url 'store:checkout' %}" class="btn btn-primary">CHECKOUT</button>
                {% endif %}
                        
        </div>
    </div>
    <!-- cart area end -->

    <script>
        $(document).ready(function(){
            $('[data-bs-toggle="tooltip"]').tooltip();
        });
    </script>
    
{% endblock %}

store/templates/store/done.html
{% extends "store/base.html" %}
{% block content %}
<div class="container" style="margin-top: 15%; margin-bottom: 20%;">
    <h1>Your payment was successful</h1>
    <p>Your payment has been processed successfully.</p>
</div>
 {% endblock %}

store/templates/store/order_address.html
{% extends 'store/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="shop-card">
    <div class="container">
        <form method="post"">
            {% csrf_token %}

            {{ form|crispy }}

            <input class="btn btn-outline-primary" type="submit" value="Continue To Payment">
        </form>


        
    </div>
</div>

{% endblock %}

store/templates/store/process.html
{% extends 'store/base.html' %}
{% block content %}

<div class="container" style="margin-top: 8em">
    <form id="payment" method="post"  action="{% url 'store:process' %}">

        <div style="width: 50%; margin: auto">
        <h1 style="margin-bottom: 1em">Pay by credit card</h1>

        <div class="form-group">
            <label for="card-number">Card Number</label>
            <div id="card-number" class="form-control"></div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="cvv">CVV</label>
                <div id="cvv" class="form-control"></div>
          </div>
          <div class="form-group col-md-6">
            <label for="expiration-date">Expiration Date</label>
            <div id="expiration-date" class="form-control"></div>
          </div>
          </div>
        <input type="hidden" id="nonce" name="payment_method_nonce" value="">
        {% csrf_token %}
        
        <p>Total: &euro; {{order.get_total_cost}}</p>
        
        <input type="submit" class="btn btn-primary" value="Pay"></div>
    </div>
      </form>


</div>
    <!-- includes the Braintree JS client SDK -->
    <script src="https://js.braintreegateway.com/web/3.44.2/js/client.min.js"></script>
    <script src="https://js.braintreegateway.com/web/3.44.2/js/hosted-fields.min.js"></script>
    <script>
        var form = document.querySelector('#payment');
        var submit = document.querySelector('input[type="submit"]');
        braintree.client.create({
            authorization: '{{ client_token }}'
        }, function (clientErr, clientInstance) {
            if (clientErr) {
                console.error(clientErr);
                return;
            }
            braintree.hostedFields.create({
                client: clientInstance,
                styles: {
                    'input': { 'font-size': '13px' },
                    'input.invalid': { 'color': 'red' },
                    'input.valid': { 'color': 'green' }
                },
                fields: {
                    number: { selector: '#card-number' },
                    cvv: { selector: '#cvv' },
                    expirationDate: { selector: '#expiration-date' }
                }
            }, function (hostedFieldsErr, hostedFieldsInstance) {
                if (hostedFieldsErr) {
                    console.error(hostedFieldsErr);
                    return;
                }
                submit.removeAttribute('disabled');
                form.addEventListener('submit', function (event) {
                    event.preventDefault();
                    hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
                        if (tokenizeErr) {
                            console.error(tokenizeErr);
                            return;
                        }
                        // set nonce to send to the server
                        document.getElementById('nonce').value = payload.nonce;
                        // submit form
                        document.getElementById('payment').submit();
                    });
                }, false);
            });
        });
    </script>

{% endblock %}