accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('login/', views.LoginView.as_view(), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path("register/", views.user_registration, name="registration"),
]

api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
# router.register(r'posts', views.PostViewSet)
# router.register(r'comments', views.CommentViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('posts/', views.PostListView.as_view()),
    path('comments/', views.CommentListView.as_view()),
    path('comment-create/', views.CommentCreateView.as_view()),
    path('comment-update/<int:pk>/', views.CommentUpdateDeleteView.as_view()),
    path('post-create/', views.PostCreateView.as_view()),
    path('post-update/<int:pk>/', views.PostUpdateDeleteView.as_view(), name='manufacturers'),
    path('register/', views.UserCreateView.as_view()),
    

]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path('', views.blog_main, name='blog'),
    # path('', views.PostListView.as_view(), name="blog"),
    path('', views.post_list, name="blog"),
    path('tag/<slug:tag_slug>/', views.post_list, name="list_by_tag"),
    path('category/<int:pk>/', views.post_list, name="list_by_categ"),
    path('post/<int:id>/', views.post_detail, name='post_detail'),
    path('new/', views.PostCreateView.as_view(), name='create_post'),
    path('edit/<int:pk>/', views.PostEditView.as_view(), name='edit_post'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete_post'),
    path('comment/<int:pk>/', views.add_comment, name='add_comment'),
    path('search/', views.basic_search, name='search'),
    
]

blueprint/urls.py
from tkinter import N
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('store/', include('store.urls', namespace='store')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.db.models.expressions import F
from taggit.managers import TaggableManager

# Create your models here.

class Category(models.Model):
    class Meta:
        verbose_name_plural = 'categories'

    categ_type = models.CharField(max_length=120)

    def __str__(self):
        return self.categ_type

class BlogPost(models.Model):
    title = models.CharField(max_length=250)
    title_image = models.ImageField(upload_to='posts/%d/%m/%Y')
    # content = models.TextField()
    content = RichTextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User, related_name='post_author', on_delete=models.SET_NULL, null=True)
    views = models.IntegerField(default=0)
    tags = TaggableManager()

    category = models.ForeignKey(Category, related_name='post_category', on_delete=models.SET_NULL, null=True)    


    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title


class PostComment(models.Model):
    author = models.ForeignKey(
        User, related_name='comment_author', on_delete=models.CASCADE, null=True, blank=True)
    post = models.ForeignKey(
        BlogPost, related_name='post_comments', on_delete=models.CASCADE, null=False)
    name = models.CharField(max_length=250, blank=False)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=100)
    content = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if self.author is not None:
            if self.author.first_name and self.author.last_name:
                self.name = self.author.first_name + ' ' + self.author.last_name
            else:
                self.name = self.author.username
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Comment {self.subject} by {self.name}"

blog/forms.py
from django import forms
from django.forms import ModelForm, widgets
from .models import BlogPost, PostComment

#not needed now.
# class PostForm(ModelForm):
#   model = BlogPost
#   fields = ['title', 'title_image', 'content', 'tags']


class CommentForm(ModelForm):
  class Meta:
    model = PostComment
    fields = ['name', 'email', 'subject', 'content']
    widgets = {'name': widgets.TextInput(attrs={
                   'placeholder': 'name (user name will be displayed if logged in)'}),
               'email': widgets.TextInput(attrs={
                   "placeholder": 'email'}),
               # 'content': widgets.TextInput(attrs={
               #   "placeholder": 'comment'}),
               'subject': widgets.TextInput(attrs={
                   "placeholder": 'subject'}),

               }

blog/views.py
from django.shortcuts import redirect, render
from blog.models import BlogPost, PostComment
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from .forms import CommentForm
from django.contrib import messages
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Category


# def blog_main(request):
#     return render(request, 'blog/blog.html')

# class PostListView(ListView):

#     model = BlogPost
#     context_object_name = 'posts'
#     template_name = 'blog/blog.html'
#     paginate_by = 10

#     def get_context_data(self, **kwargs):
#       context = super(PostListView, self).get_context_data(**kwargs)
#       context['most_popular'] = BlogPost.objects.order_by('-views')[:5]
#       return context


def post_list(request, tag_slug=None, pk=None):
    tag = None
    posts = BlogPost.objects.all()
    
    if tag_slug:
      tag = get_object_or_404(Tag, slug=tag_slug)
      posts = posts.filter(tags__in=[tag])

    if pk:
      category = get_object_or_404(Category, pk=pk)
      posts = posts.filter(category__in=[category])

    paginator = Paginator(posts, 6)
    page = request.GET.get('page')
    try:
      posts = paginator.page(page)
    except PageNotAnInteger:
      # If page is not an integer deliver the first page
      posts = paginator.page(1)
    except EmptyPage:
      # If page is out of range deliver last page of results
      posts = paginator.page(paginator.num_pages)

    context = {
      'most_popular': BlogPost.objects.order_by('-views')[:5],
      'posts': posts,
      'page': posts,
      'tags': Tag.objects.all(),
      'categories': Category.objects.all(),
    }

    return render(request, 'blog/blog.html', context)

def post_detail(request, id):
    post = get_object_or_404(BlogPost, id=id)
    post.views += 1
    post.save()

    comment_form = CommentForm()
    post_comments = PostComment.objects.filter(post__id=id)

    #repeating code, but otherwise the base.html gets messed up when I try to use inheritance.
    #TODO: fix 
    context = {
      'most_popular': BlogPost.objects.order_by('-views')[:5],
      'post': post,
      'comment_form': comment_form,
      'post_comments': post_comments,
      'tags': Tag.objects.all(),
      'categories': Category.objects.all(),
      }
    return render(request, 'blog/post-details.html', context)


def add_comment(request, pk):
  post = get_object_or_404(BlogPost, id=pk)
  comment_form = CommentForm()
  if request.method == 'POST':
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
      comment = comment_form.save(commit=False)
      try:
        comment.author = request.user
      except ValueError:
        comment.author = None
      comment.post = post
      comment.save()
      messages.success(request, 'Comment has been posted.')  
  
  return redirect('blog:post_detail', post.id)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = BlogPost
    fields = ['title', 'category', 'title_image', 'content', 'tags']
    template_name = 'blog/new.html'

    def form_valid(self, form):
      self.object = form.save(commit=False)
      self.object.author = self.request.user
      self.object.save()
      return super().form_valid(form)

    #get obj id and reverse to post/id
    def get_success_url(self):
      return reverse('blog:post_detail', args=(self.object.id,))

    
class PostEditView(LoginRequiredMixin, UpdateView):
    model = BlogPost
    fields = ['title', 'category', 'title_image', 'content', 'tags']
    template_name = 'blog/edit.html'

    def get_context_data(self, **kwargs):
      context = super(PostEditView, self).get_context_data(**kwargs)
      context['post'] = self.object
      return context

    def dispatch(self, request, *args, **kwargs):
      post = self.get_object()
      if not (request.user == post.author or request.user.is_superuser):
          return self.handle_no_permission()
      return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
      return reverse('blog:post_detail', args=(self.object.id,))


class PostDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('blog:blog')
    template_name = 'blog/delete.html'
    

def basic_search(request):
    #TODO: when working on server that supports PSQL, change to SearchVector    
    term = request.GET['term']
    results = BlogPost.objects.filter(title__icontains=term) | \
        BlogPost.objects.filter(content__icontains=term)

    paginator = Paginator(results, 1)
    page = request.GET.get('page')
    try:
      results = paginator.page(page)
    except PageNotAnInteger:
      # If page is not an integer deliver the first page
      results = paginator.page(1)
    except EmptyPage:
      # If page is out of range deliver last page of results
      results = paginator.page(paginator.num_pages)
      
    context = {'results': results,
              'term': term,
              'tags': Tag.objects.all(), 
              'page': results,
              'categories': Category.objects.all(),
              }    
            
    return render(request, 'blog/search_result.html', context)
    # else:
    #   return render(request, 'blog/search_result.html')

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <title>Stand Blog Posts</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static "assets/css/fontawesome.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/templatemo-stand-blog.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/owl.css" %}">
<!--

TemplateMo 551 Stand Blog

https://templatemo.com/tm-551-stand-blog

-->
  </head>

  <body>


    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div  class="container">
          <a class="navbar-brand" href="{% url 'blog:blog' %}"><h2>Stand Blog<em>.</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
                <li class="nav-item">                
                    <a class="nav-link" href="{% url 'blog:create_post' %}">New Blog Post</a>
                </li>
                <!-- <li class="nav-item">                
                    <a class="nav-link" href="contact.html">Profile</a>
                </li>                 -->
                <li class="nav-item">                
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                </li>
              {% else %}
                <li class="nav-item">                
                    <a class="nav-link" href="{% url 'accounts:login' %}">Log in/Register</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <!-- Page Content -->
    
    {% for message in messages %}
      <div style="margin-top: 15px; width: 95%; text-align: center; margin-left: auto; margin-right: auto" class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}

    {% block content %}

    {% endblock %}

    
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <ul class="social-icons">
              <li><a href="#">Facebook</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Behance</a></li>
              <li><a href="#">Linkedin</a></li>
              <li><a href="#">Dribbble</a></li>
            </ul>
          </div>
          <div class="col-lg-12">
            <div class="copyright-text">
              <p>Copyright 2020 Stand Blog Co.
                    
                 | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
            </div>
          </div>
        </div>
      </div>
    </footer>


    <!-- Bootstrap core JavaScript -->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static "assets/js/custom.js" %}"></script>
    <script src="{% static "assets/js/owl.js" %}"></script>
    <script src="{% static "assets/js/slick.js" %}"></script>
    <script src="{% static "assets/js/isotope.js" %}"></script>
    <script src="{% static "assets/js/accordions.js" %}"></script>

    <script language = "text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>

  </body>
</html>

blog/templates/blog/blog.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<!-- Banner Starts Here -->
<div class="heading-page header-text">
  <section class="page-heading">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="text-content">
            <h4>Recent Posts</h4>
            <h2>Our Recent Blog Entries</h2>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<!-- Banner Ends Here -->
    
<section class="blog-posts">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                <div class="col-lg-12">

                  {% for post in posts %}
                    <div class="blog-post">
                      <div class="blog-thumb">
                        <img src=/media/{{post.title_image}} alt="">
                      </div>
                      <div class="down-content">
                        <span>{{ post.category }}</span>
                        <a href="{% url 'blog:post_detail' post.id %}"><h4>{{ post.title }}</h4></a>
                        <ul class="post-info">
                          <li><a href="#">{{ post.author }}</a></li>
                          <li><a href="#">{{ post.created }}</a></li>
                          <li><a href="#">{{ post.post_comments.count }} comment{{ post.post_comments.count|pluralize }}</a></li>
                        </ul>
                        <p>{{ post.content|safe|truncatechars:350 }}</p>
                        <div class="post-options">
                          <div class="row">
                            <div class="col-lg-8">
                              <ul class="post-tags">
                                <li><i class="fa fa-tags"></i></li>

                                {% for tag in post.tags.all %}
                                  <li><a href="{% url "blog:list_by_tag" tag.slug %}">{{ tag|title }}</a>,</li>
                                {% endfor %}
                                
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  {% endfor %}

                </div> 

                <!-- Default Paginator from template-->
                <!-- <div class="col-lg-12">
                  <ul class="page-numbers">
                    <li><a href="#">1</a></li>
                    <li class="active"><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#"><i class="fa fa-angle-double-right"></i></a></li>
                  </ul>
                </div> -->

              <!-- Mine: -->
              <!-- Now changed to work w/ a Paginator obj in a FBV
              instead of a CBV. For CBF, see GH repo. -->
                <div class="col-lg-12">
                  <ul class="page-numbers">
                        {% if page.has_previous %}
                            <li><a href="?page=1">&laquo; First</a></li>
                            <li><a href="?page={{ page.previous_page_number }}">{{ page.previous_page_number }}</a></li>
                        {% endif %}                
                        <li class="active"><a href="#">{{ page.number }}</a></li>                
                        {% if page.has_next %}
                            <li><a href="?page={{ page.next_page_number }}">{{ page.next_page_number }}</a></li>
                            <li><a href="?page={{ page.paginator.num_pages }}">Last &raquo;</a></li>
                        {% endif %}
                  </ul>
                </div>
              <!-- ednfrom -->

              </div>
            </div>
          </div>
          
          <div class="col-lg-4">
            <div class="sidebar">
              <div class="row">
                <div class="col-lg-12">
                  <div class="sidebar-item search">
                    <form id="search_form"  action="{% url 'blog:search' %}">
                      <input type="text" name='term' class="searchText" placeholder="type to search..." autocomplete="on">
                    </form>
                  </div>
                </div>

                <div class="col-lg-12">
                  <div class="sidebar-item recent-posts">
                    <div class="sidebar-heading">
                      <h2>Most Popular Posts</h2>
                    </div>

                    <div class="content">
                      {% for post in most_popular %}
                        <ul>
                          <li><a href="{% url "blog:post_detail" post.id %}">
                            <h5>{{ post.title }}</h5>
                            <span>{{ post.created }}</span>
                          </a></li>                          
                        </ul>
                      {% endfor %}
                    </div>

                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item categories">
                    <div class="sidebar-heading">
                      <h2>Categories</h2>
                    </div>
                    <div class="content">
                      <ul>
                        {% for category in categories %}
                          <li><a href="{% url 'blog:list_by_categ' category.pk %}">{{ category }}</a></li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item tags">
                    <div class="sidebar-heading">
                      <h2>Tags</h2>
                    </div>
                    <div class="content">
                      <ul>
                        {% for tag in tags %}
                          <li><a href="{% url "blog:list_by_tag" tag.slug %}">{{ tag|title }}</a></li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


{% endblock %}
    

blog/templates/blog/edit.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<form class="custom-form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    {{ form.media }}
    <div style="display: inline-block; width: 100%;">
        <input class='btn btn-outline-success btn-lg btn-block' type="submit" value="Update">
        <a class='btn btn-outline-danger btn-lg btn-block' href="{% url 'blog:delete_post' post.pk %}">Delete Post</a>
    </div>
</form>
{% endblock %}

blog/templates/blog/post-details.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

  {% block content %}

    <section class="blog-posts grid-system">

      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
        {% endfor %}
      {% endif %}
      
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                <div class="col-lg-12">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src=/media/{{post.title_image}} alt="">
                    </div>
                    <div class="down-content">
                      <span>{{ post.category }}</span>

                        <div style="display: inline-block; width: 100%;">
                          <a style="float: left;"><h4>{{ post.title }}</h4></a>                          
                          {% if request.user == post.author %}
                            <a style="float: right;" class="btn btn-outline-danger" href="{% url "blog:edit_post" post.pk %}">Edit Post</a>
                          {% endif %}
                        </div>

                      <ul class="post-info">
                        <li><a href="#">{{ post.author }}</a></li>
                        <li><a href="#">{{ post.created }}</a></li>
                        <li><a href="#">{{ post.post_comments.count}} comment{{ post.post_comments.count|pluralize }}</a></li>
                      </ul>
                      <p>
                        {{ post.content|safe }}
                      </p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">                              
                              <li><i class="fa fa-tags"></i></li>

                              {% for tag in post.tags.all %}
                                <li><a href="{% url "blog:list_by_tag" tag.slug %}">{{ tag|title }}</a>,</li>
                              {% endfor %}
                            </ul>
                            
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="#">Facebook</a>,</li>
                              <li><a href="#"> Twitter</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="col-lg-12">
                  <div class="sidebar-item comments">
                    <div class="sidebar-heading">
                      <h2>{{ post_comments.count }} comment{{ post.post_comments.count|pluralize }}</h2>
                    </div>
                    <div class="content">    
                      <ul>

                        {% for comment in post_comments %}
                          <li>
                            <div class="author-thumb">
                              <img src="assets/images/comment-author-01.jpg" alt="">
                            </div>
                            <div class="right-content">
                              <h4>{{ comment.name }}<span>{{ comment.date_added }}</span></h4>
                              <p>{{ comment.content }}</p>
                            </div>
                          </li>
                        {% endfor %}

                        <!-- For comment replies. Perhaps add functionality later. -->

                        <!-- <li class="replied">
                          <div class="author-thumb">
                            <img src="assets/images/comment-author-02.jpg" alt="">
                          </div>
                          <div class="right-content">
                            <h4>Thirteen Man<span>May 20, 2020</span></h4>
                            <p>In porta urna sed venenatis sollicitudin. Praesent urna sem, pulvinar vel mattis eget.</p>
                          </div>
                        </li> -->

                      </ul>
                    </div>
                  </div>
                </div>

                <div class="col-lg-12">
                  <div class="sidebar-item submit-comment">
                    <div class="sidebar-heading">
                      <h2>Your comment</h2>
                    </div>
                    <div class="content">
                      <form id="comment" action="{% url "blog:add_comment" post.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                          <div class="col-md-6 col-sm-12">
                            <fieldset>
                              <p name="name" type="text" id="name" placeholder="Your name" required="">{{ comment_form.name}}</p>
                            </fieldset>
                          </div>
                          <div class="col-md-6 col-sm-12">
                            <fieldset>
                              <p name="email" type="text" id="email" placeholder="Your email" required="">{{ comment_form.email }}</p>
                            </fieldset>
                          </div>
                          <div class="col-md-12 col-sm-12">
                            <fieldset>
                              <p name="subject" type="text" id="subject" placeholder="Subject">{{ comment_form.subject }}</p>
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <p name="message" rows="6" id="message" placeholder="Type your comment" required="">{{ comment_form.content }}</p>
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <button type="submit" id="form-submit" class="main-button">Submit</button>
                            </fieldset>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="sidebar">
              <div class="row">
                <div class="col-lg-12">
                  <div class="sidebar-item search">
                    <form id="search_form" method="POST" action="{% url 'blog:search' %}">
                      {% csrf_token %}
                      <input type="text" name='term' class="searchText" placeholder="type to search..." autocomplete="on">
                    </form>
                  </div>
                </div>

                <div class="col-lg-12">
                  <div class="sidebar-item recent-posts">
                    <div class="sidebar-heading">
                      <h2>Most Popular Posts</h2>
                    </div>

                    <div class="content">
                      {% for post in most_popular %}
                        <ul>
                          <li><a href="{% url "blog:post_detail" post.id %}">
                            <h5>{{ post.title }}</h5>
                            <span>{{ post.created }}</span>
                          </a></li>                          
                        </ul>
                      {% endfor %}
                    </div>
                  </div>

                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item categories">
                    <div class="sidebar-heading">
                      <h2>Categories</h2>
                    </div>
                    <div class="content">
                      <ul>
                        {% for category in categories %}
                          <li><a href="{% url 'blog:list_by_categ' category.pk %}">{{ category }}</a></li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item tags">
                    <div class="sidebar-heading">
                      <h2>Tags</h2>
                    </div>
                    <div class="content">
                      <ul>
                        {% for tag in tags %}
                          <li><a href="{% url "blog:list_by_tag" tag.slug %}">{{ tag|title }}</a></li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}

    