api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
# router.register(r'posts', views.PostViewSet)
# router.register(r'comments', views.CommentViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('posts/', views.PostListView.as_view()),
    path('comments/', views.CommentListView.as_view()),
    path('comment-create/', views.CommentCreateView.as_view()),
    path('comment-update/<int:pk>/', views.CommentUpdateDeleteView.as_view()),
    path('post-create/', views.PostCreateView.as_view()),
    path('post-update/<int:pk>/', views.PostUpdateDeleteView.as_view(), name='manufacturers'),
    path('register/', views.UserCreateView.as_view()),
    

]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path('', views.blog_main, name='blog'),
    # path('', views.PostListView.as_view(), name="blog"),
    path('', views.post_list, name="blog"),
    path('tag/<slug:tag_slug>/', views.post_list, name="list_by_tag"),
    path('category/<int:pk>/', views.post_list, name="list_by_categ"),
    path('post/<int:id>/', views.post_detail, name='post_detail'),
    path('new/', views.PostCreateView.as_view(), name='create_post'),
    path('edit/<int:pk>/', views.PostEditView.as_view(), name='edit_post'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete_post'),
    path('comment/<int:pk>/', views.add_comment, name='add_comment'),
    path('search/', views.basic_search, name='search'),
    
]

blueprint/urls.py
from tkinter import N
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('store/', include('store.urls', namespace='store')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.main, name="store_index"),
    path('filter/', views.FilterListView.as_view(), name='filter'),
    path('products/', views.ProductListView.as_view(), name="store_products"),
    path('category/<str:category>', views.FilterListView.as_view(), name="category"),
    path('product/<int:pk>', views.single_product, name="product"),
    path('order/', views.order_process_view, name="order"),
    path('cart/', views.cart_view, name="cart"),
    path('remove/<int:id>/', views.cart_remove, name='cart_remove'),
    path('update/<int:id>/', views.cart_update, name='cart_update'),
    path('checkout/', views.order_address, name='checkout'),
    # path('payment', views.payment_process, name='payment'),
    path('process/', views.payment_process, name='process'),
    path('done/', views.payment_done, name='done'),
    path('canceled/', views.payment_canceled, name='canceled'),
]

index/templates/index/index.html
{% load static %}
<!Doctype html>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<link href="{% static "style.css" %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<main class="Loop js-loop">
  <a style="color: inherit" href="http://#">
    <i class="fa fa-github right-badge" style="font-size:36px"></i>
  </a>
    <section class="one">
      <div class="text">
        <a href="{% url "blog:blog" %}"><h1 class="pulsate">BLOG</h1></a>
        <p>
          {{ blog_info }}
          <p style="text-transform: none; padding-top: 15px">
            test account: username: demo_user, password: demo
          </p>
        </p>
    </div>
    </section>
    <section class="two">
      <div class="text">
        <a href="{% url "store:store_index" %}"><h1 class="pulsate">STORE</h1></a>
        <p>
          {{ store_info }}
        </p>
    </div>

    </section>
    <section class="three">
      <div class="text">
        <a href="http://localhost:8000/api/"><h1 class="pulsate">API</h1></a>
          <p>
            {{ api_info }}
          </p>
          {% autoescape off %}
            {{ api_links }}
          {% endautoescape %}
          <h3>token!</h3>
      </div>
    </section>
    <!-- <section class="four">
      <h1>And</h1>
    </section>
    <section class="three">
      <h1>All</h1>
    </section>
    <section class="two">
      <h1>For</h1>
    </section> -->
  
    <!--
    These blocks are the same as the first blocks to get that looping illusion going.
    You need to add clones to fill out a full viewport height.
    -->
    <section class="one is-clone">
      <div class="text">
        <a href="{% url "blog:blog" %}"><h1 class="pulsate">BLOG</h1></a>
        <p>
          {{ blog_info }}
          <p style="text-transform: none; padding-top: 15px">
            test account: username: demo_user, password: demo
          </p>
        </p>
    </div>
    </section>

    <section class="two is-clone">
      <div class="text">
        <a href="{% url "store:store_index" %}"><h1 class="pulsate">STORE</h1></a>
        <p>
        {{ store_info }}
        </p>
    </div>
    </section>

  </main>

<script type="text/javascript">

    var doc = window.document,
    context = doc.querySelector('.js-loop'),
    clones = context.querySelectorAll('.is-clone'),
    disableScroll = false,
    scrollHeight = 0,
    scrollPos = 0,
    clonesHeight = 0,
    i = 0;

  function getScrollPos () {
    return (context.pageYOffset || context.scrollTop) - (context.clientTop || 0);
  }

  function setScrollPos (pos) {
    context.scrollTop = pos;
  }

  function getClonesHeight () {
    clonesHeight = 0;

    for (i = 0; i < clones.length; i += 1) {
      clonesHeight = clonesHeight + clones[i].offsetHeight;
    }

    return clonesHeight;
  }

  function reCalc () {
    scrollPos = getScrollPos();
    scrollHeight = context.scrollHeight;
    clonesHeight = getClonesHeight();

    if (scrollPos <= 0) {
      setScrollPos(1); // Scroll 1 pixel to allow upwards scrolling
    }
  }

  function scrollUpdate () {
    if (!disableScroll) {
      scrollPos = getScrollPos();

      if (clonesHeight + scrollPos >= scrollHeight) {
        // Scroll to the top when you’ve reached the bottom
        setScrollPos(1); // Scroll down 1 pixel to allow upwards scrolling
        disableScroll = true;
      } else if (scrollPos <= 0) {
        // Scroll to the bottom when you reach the top
        setScrollPos(scrollHeight - clonesHeight);
        disableScroll = true;
      }
    }

    if (disableScroll) {
      // Disable scroll-jumping for a short time to avoid flickering
      window.setTimeout(function () {
        disableScroll = false;
      }, 40);
    }
  }

  function init () {
    reCalc();
    
    context.addEventListener('scroll', function () {
      window.requestAnimationFrame(scrollUpdate);
    }, false);

    window.addEventListener('resize', function () {
      window.requestAnimationFrame(reCalc);
    }, false);
  }

  if (document.readyState !== 'loading') {
    init()
  } else {
    doc.addEventListener('DOMContentLoaded', init, false)
  }

</script>

<!-- 
Copyright (c) 2022 by Vincent Orback (https://codepen.io/vincentorback/pen/zxRyzj)

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated 
documentation files (the "Software"), to deal in the Software without restriction, including without 
limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the 
Software, and to permit persons to whom the Software is furnished to do so, subject to the following 
conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions 
of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED 
TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
DEALINGS IN THE SOFTWARE.
 -->